# Generated by Django 3.1.6 on 2021-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password1', models.CharField(blank=True, max_length=100, null=True)),
                ('password2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
